package de.bauhd.sculk.entity;

/**
 * All entity types possible.
 */
public enum EntityType {

    // START
    ALLAY("minecraft:allay"),
    AREA_EFFECT_CLOUD("minecraft:area_effect_cloud"),
    ARMOR_STAND("minecraft:armor_stand"),
    ARROW("minecraft:arrow"),
    AXOLOTL("minecraft:axolotl"),
    BAT("minecraft:bat"),
    BEE("minecraft:bee"),
    BLAZE("minecraft:blaze"),
    BLOCK_DISPLAY("minecraft:block_display"),
    BOAT("minecraft:boat"),
    CAMEL("minecraft:camel"),
    CAT("minecraft:cat"),
    CAVE_SPIDER("minecraft:cave_spider"),
    CHEST_BOAT("minecraft:chest_boat"),
    CHEST_MINECART("minecraft:chest_minecart"),
    CHICKEN("minecraft:chicken"),
    COD("minecraft:cod"),
    COMMAND_BLOCK_MINECART("minecraft:command_block_minecart"),
    COW("minecraft:cow"),
    CREEPER("minecraft:creeper"),
    DOLPHIN("minecraft:dolphin"),
    DONKEY("minecraft:donkey"),
    DRAGON_FIREBALL("minecraft:dragon_fireball"),
    DROWNED("minecraft:drowned"),
    EGG("minecraft:egg"),
    ELDER_GUARDIAN("minecraft:elder_guardian"),
    END_CRYSTAL("minecraft:end_crystal"),
    ENDER_DRAGON("minecraft:ender_dragon"),
    ENDER_PEARL("minecraft:ender_pearl"),
    ENDERMAN("minecraft:enderman"),
    ENDERMITE("minecraft:endermite"),
    EVOKER("minecraft:evoker"),
    EVOKER_FANGS("minecraft:evoker_fangs"),
    EXPERIENCE_BOTTLE("minecraft:experience_bottle"),
    EXPERIENCE_ORB("minecraft:experience_orb"),
    EYE_OF_ENDER("minecraft:eye_of_ender"),
    FALLING_BLOCK("minecraft:falling_block"),
    FIREWORK_ROCKET("minecraft:firework_rocket"),
    FOX("minecraft:fox"),
    FROG("minecraft:frog"),
    FURNACE_MINECART("minecraft:furnace_minecart"),
    GHAST("minecraft:ghast"),
    GIANT("minecraft:giant"),
    GLOW_ITEM_FRAME("minecraft:glow_item_frame"),
    GLOW_SQUID("minecraft:glow_squid"),
    GOAT("minecraft:goat"),
    GUARDIAN("minecraft:guardian"),
    HOGLIN("minecraft:hoglin"),
    HOPPER_MINECART("minecraft:hopper_minecart"),
    HORSE("minecraft:horse"),
    HUSK("minecraft:husk"),
    ILLUSIONER("minecraft:illusioner"),
    INTERACTION("minecraft:interaction"),
    IRON_GOLEM("minecraft:iron_golem"),
    ITEM("minecraft:item"),
    ITEM_DISPLAY("minecraft:item_display"),
    ITEM_FRAME("minecraft:item_frame"),
    FIREBALL("minecraft:fireball"),
    LEASH_KNOT("minecraft:leash_knot"),
    LIGHTNING_BOLT("minecraft:lightning_bolt"),
    LLAMA("minecraft:llama"),
    LLAMA_SPIT("minecraft:llama_spit"),
    MAGMA_CUBE("minecraft:magma_cube"),
    MARKER("minecraft:marker"),
    MINECART("minecraft:minecart"),
    MOOSHROOM("minecraft:mooshroom"),
    MULE("minecraft:mule"),
    OCELOT("minecraft:ocelot"),
    PAINTING("minecraft:painting"),
    PANDA("minecraft:panda"),
    PARROT("minecraft:parrot"),
    PHANTOM("minecraft:phantom"),
    PIG("minecraft:pig"),
    PIGLIN("minecraft:piglin"),
    PIGLIN_BRUTE("minecraft:piglin_brute"),
    PILLAGER("minecraft:pillager"),
    POLAR_BEAR("minecraft:polar_bear"),
    POTION("minecraft:potion"),
    PUFFERFISH("minecraft:pufferfish"),
    RABBIT("minecraft:rabbit"),
    RAVAGER("minecraft:ravager"),
    SALMON("minecraft:salmon"),
    SHEEP("minecraft:sheep"),
    SHULKER("minecraft:shulker"),
    SHULKER_BULLET("minecraft:shulker_bullet"),
    SILVERFISH("minecraft:silverfish"),
    SKELETON("minecraft:skeleton"),
    SKELETON_HORSE("minecraft:skeleton_horse"),
    SLIME("minecraft:slime"),
    SMALL_FIREBALL("minecraft:small_fireball"),
    SNIFFER("minecraft:sniffer"),
    SNOW_GOLEM("minecraft:snow_golem"),
    SNOWBALL("minecraft:snowball"),
    SPAWNER_MINECART("minecraft:spawner_minecart"),
    SPECTRAL_ARROW("minecraft:spectral_arrow"),
    SPIDER("minecraft:spider"),
    SQUID("minecraft:squid"),
    STRAY("minecraft:stray"),
    STRIDER("minecraft:strider"),
    TADPOLE("minecraft:tadpole"),
    TEXT_DISPLAY("minecraft:text_display"),
    TNT("minecraft:tnt"),
    TNT_MINECART("minecraft:tnt_minecart"),
    TRADER_LLAMA("minecraft:trader_llama"),
    TRIDENT("minecraft:trident"),
    TROPICAL_FISH("minecraft:tropical_fish"),
    TURTLE("minecraft:turtle"),
    VEX("minecraft:vex"),
    VILLAGER("minecraft:villager"),
    VINDICATOR("minecraft:vindicator"),
    WANDERING_TRADER("minecraft:wandering_trader"),
    WARDEN("minecraft:warden"),
    WITCH("minecraft:witch"),
    WITHER("minecraft:wither"),
    WITHER_SKELETON("minecraft:wither_skeleton"),
    WITHER_SKULL("minecraft:wither_skull"),
    WOLF("minecraft:wolf"),
    ZOGLIN("minecraft:zoglin"),
    ZOMBIE("minecraft:zombie"),
    ZOMBIE_HORSE("minecraft:zombie_horse"),
    ZOMBIE_VILLAGER("minecraft:zombie_villager"),
    ZOMBIFIED_PIGLIN("minecraft:zombified_piglin"),
    PLAYER("minecraft:player"),
    FISHING_BOBBER("minecraft:fishing_bobber"),
    // END
    ;

    private final String key;

    EntityType(final String key) {
        this.key = key;
    }

    public String key() {
        return this.key;
    }
}
