package de.bauhd.sculk.entity;

/**
 * All entity types possible.
 */
public enum EntityType {

    // START
    ALLAY("minecraft:allay", 0),
    AREA_EFFECT_CLOUD("minecraft:area_effect_cloud", 1),
    ARMOR_STAND("minecraft:armor_stand", 2),
    ARROW("minecraft:arrow", 3),
    AXOLOTL("minecraft:axolotl", 4),
    BAT("minecraft:bat", 5),
    BEE("minecraft:bee", 6),
    BLAZE("minecraft:blaze", 7),
    BLOCK_DISPLAY("minecraft:block_display", 8),
    BOAT("minecraft:boat", 9),
    CAMEL("minecraft:camel", 10),
    CAT("minecraft:cat", 11),
    CAVE_SPIDER("minecraft:cave_spider", 12),
    CHEST_BOAT("minecraft:chest_boat", 13),
    CHEST_MINECART("minecraft:chest_minecart", 14),
    CHICKEN("minecraft:chicken", 15),
    COD("minecraft:cod", 16),
    COMMAND_BLOCK_MINECART("minecraft:command_block_minecart", 17),
    COW("minecraft:cow", 18),
    CREEPER("minecraft:creeper", 19),
    DOLPHIN("minecraft:dolphin", 20),
    DONKEY("minecraft:donkey", 21),
    DRAGON_FIREBALL("minecraft:dragon_fireball", 22),
    DROWNED("minecraft:drowned", 23),
    EGG("minecraft:egg", 24),
    ELDER_GUARDIAN("minecraft:elder_guardian", 25),
    END_CRYSTAL("minecraft:end_crystal", 26),
    ENDER_DRAGON("minecraft:ender_dragon", 27),
    ENDER_PEARL("minecraft:ender_pearl", 28),
    ENDERMAN("minecraft:enderman", 29),
    ENDERMITE("minecraft:endermite", 30),
    EVOKER("minecraft:evoker", 31),
    EVOKER_FANGS("minecraft:evoker_fangs", 32),
    EXPERIENCE_BOTTLE("minecraft:experience_bottle", 33),
    EXPERIENCE_ORB("minecraft:experience_orb", 34),
    EYE_OF_ENDER("minecraft:eye_of_ender", 35),
    FALLING_BLOCK("minecraft:falling_block", 36),
    FIREBALL("minecraft:fireball", 57),
    FIREWORK_ROCKET("minecraft:firework_rocket", 37),
    FISHING_BOBBER("minecraft:fishing_bobber", 123),
    FOX("minecraft:fox", 38),
    FROG("minecraft:frog", 39),
    FURNACE_MINECART("minecraft:furnace_minecart", 40),
    GHAST("minecraft:ghast", 41),
    GIANT("minecraft:giant", 42),
    GLOW_ITEM_FRAME("minecraft:glow_item_frame", 43),
    GLOW_SQUID("minecraft:glow_squid", 44),
    GOAT("minecraft:goat", 45),
    GUARDIAN("minecraft:guardian", 46),
    HOGLIN("minecraft:hoglin", 47),
    HOPPER_MINECART("minecraft:hopper_minecart", 48),
    HORSE("minecraft:horse", 49),
    HUSK("minecraft:husk", 50),
    ILLUSIONER("minecraft:illusioner", 51),
    INTERACTION("minecraft:interaction", 52),
    IRON_GOLEM("minecraft:iron_golem", 53),
    ITEM("minecraft:item", 54),
    ITEM_DISPLAY("minecraft:item_display", 55),
    ITEM_FRAME("minecraft:item_frame", 56),
    LEASH_KNOT("minecraft:leash_knot", 58),
    LIGHTNING_BOLT("minecraft:lightning_bolt", 59),
    LLAMA("minecraft:llama", 60),
    LLAMA_SPIT("minecraft:llama_spit", 61),
    MAGMA_CUBE("minecraft:magma_cube", 62),
    MARKER("minecraft:marker", 63),
    MINECART("minecraft:minecart", 64),
    MOOSHROOM("minecraft:mooshroom", 65),
    MULE("minecraft:mule", 66),
    OCELOT("minecraft:ocelot", 67),
    PAINTING("minecraft:painting", 68),
    PANDA("minecraft:panda", 69),
    PARROT("minecraft:parrot", 70),
    PHANTOM("minecraft:phantom", 71),
    PIG("minecraft:pig", 72),
    PIGLIN("minecraft:piglin", 73),
    PIGLIN_BRUTE("minecraft:piglin_brute", 74),
    PILLAGER("minecraft:pillager", 75),
    PLAYER("minecraft:player", 122),
    POLAR_BEAR("minecraft:polar_bear", 76),
    POTION("minecraft:potion", 77),
    PUFFERFISH("minecraft:pufferfish", 78),
    RABBIT("minecraft:rabbit", 79),
    RAVAGER("minecraft:ravager", 80),
    SALMON("minecraft:salmon", 81),
    SHEEP("minecraft:sheep", 82),
    SHULKER("minecraft:shulker", 83),
    SHULKER_BULLET("minecraft:shulker_bullet", 84),
    SILVERFISH("minecraft:silverfish", 85),
    SKELETON("minecraft:skeleton", 86),
    SKELETON_HORSE("minecraft:skeleton_horse", 87),
    SLIME("minecraft:slime", 88),
    SMALL_FIREBALL("minecraft:small_fireball", 89),
    SNIFFER("minecraft:sniffer", 90),
    SNOW_GOLEM("minecraft:snow_golem", 91),
    SNOWBALL("minecraft:snowball", 92),
    SPAWNER_MINECART("minecraft:spawner_minecart", 93),
    SPECTRAL_ARROW("minecraft:spectral_arrow", 94),
    SPIDER("minecraft:spider", 95),
    SQUID("minecraft:squid", 96),
    STRAY("minecraft:stray", 97),
    STRIDER("minecraft:strider", 98),
    TADPOLE("minecraft:tadpole", 99),
    TEXT_DISPLAY("minecraft:text_display", 100),
    TNT("minecraft:tnt", 101),
    TNT_MINECART("minecraft:tnt_minecart", 102),
    TRADER_LLAMA("minecraft:trader_llama", 103),
    TRIDENT("minecraft:trident", 104),
    TROPICAL_FISH("minecraft:tropical_fish", 105),
    TURTLE("minecraft:turtle", 106),
    VEX("minecraft:vex", 107),
    VILLAGER("minecraft:villager", 108),
    VINDICATOR("minecraft:vindicator", 109),
    WANDERING_TRADER("minecraft:wandering_trader", 110),
    WARDEN("minecraft:warden", 111),
    WITCH("minecraft:witch", 112),
    WITHER("minecraft:wither", 113),
    WITHER_SKELETON("minecraft:wither_skeleton", 114),
    WITHER_SKULL("minecraft:wither_skull", 115),
    WOLF("minecraft:wolf", 116),
    ZOGLIN("minecraft:zoglin", 117),
    ZOMBIE("minecraft:zombie", 118),
    ZOMBIE_HORSE("minecraft:zombie_horse", 119),
    ZOMBIE_VILLAGER("minecraft:zombie_villager", 120),
    ZOMBIFIED_PIGLIN("minecraft:zombified_piglin", 121),
    // END
    ;

    private final String key;
    private final int protocolId;

    EntityType(final String key, final int protocolId) {
        this.key = key;
        this.protocolId = protocolId;
    }

    public String key() {
        return this.key;
    }

    public int protocolId() {
        return this.protocolId;
    }
}
