package eu.sculkpowered.server.entity;

import eu.sculkpowered.server.entity.meta.EntityMeta;
import eu.sculkpowered.server.registry.Registries;
import net.kyori.adventure.key.Key;

@SuppressWarnings("unused")
public final class EntityTypes {

  public static final EntityType<Entity<EntityMeta>> ALLAY = get("allay");
  public static final EntityType<Entity<EntityMeta>> AREA_EFFECT_CLOUD = get("area_effect_cloud");
  public static final EntityType<Entity<EntityMeta>> ARMADILLO = get("armadillo");
  public static final EntityType<Entity<EntityMeta>> ARMOR_STAND = get("armor_stand");
  public static final EntityType<Entity<EntityMeta>> ARROW = get("arrow");
  public static final EntityType<Entity<EntityMeta>> AXOLOTL = get("axolotl");
  public static final EntityType<Entity<EntityMeta>> BAT = get("bat");
  public static final EntityType<Entity<EntityMeta>> BEE = get("bee");
  public static final EntityType<Entity<EntityMeta>> BLAZE = get("blaze");
  public static final EntityType<Entity<EntityMeta>> BLOCK_DISPLAY = get("block_display");
  public static final EntityType<Entity<EntityMeta>> BOAT = get("boat");
  public static final EntityType<Entity<EntityMeta>> BOGGED = get("bogged");
  public static final EntityType<Entity<EntityMeta>> BREEZE = get("breeze");
  public static final EntityType<Entity<EntityMeta>> BREEZE_WIND_CHARGE = get("breeze_wind_charge");
  public static final EntityType<Entity<EntityMeta>> CAMEL = get("camel");
  public static final EntityType<Entity<EntityMeta>> CAT = get("cat");
  public static final EntityType<Entity<EntityMeta>> CAVE_SPIDER = get("cave_spider");
  public static final EntityType<Entity<EntityMeta>> CHEST_BOAT = get("chest_boat");
  public static final EntityType<Entity<EntityMeta>> CHEST_MINECART = get("chest_minecart");
  public static final EntityType<Entity<EntityMeta>> CHICKEN = get("chicken");
  public static final EntityType<Entity<EntityMeta>> COD = get("cod");
  public static final EntityType<Entity<EntityMeta>> COMMAND_BLOCK_MINECART = get("command_block_minecart");
  public static final EntityType<Entity<EntityMeta>> COW = get("cow");
  public static final EntityType<Entity<EntityMeta>> CREEPER = get("creeper");
  public static final EntityType<Entity<EntityMeta>> DOLPHIN = get("dolphin");
  public static final EntityType<Entity<EntityMeta>> DONKEY = get("donkey");
  public static final EntityType<Entity<EntityMeta>> DRAGON_FIREBALL = get("dragon_fireball");
  public static final EntityType<Entity<EntityMeta>> DROWNED = get("drowned");
  public static final EntityType<Entity<EntityMeta>> EGG = get("egg");
  public static final EntityType<Entity<EntityMeta>> ELDER_GUARDIAN = get("elder_guardian");
  public static final EntityType<Entity<EntityMeta>> END_CRYSTAL = get("end_crystal");
  public static final EntityType<Entity<EntityMeta>> ENDER_DRAGON = get("ender_dragon");
  public static final EntityType<Entity<EntityMeta>> ENDER_PEARL = get("ender_pearl");
  public static final EntityType<Entity<EntityMeta>> ENDERMAN = get("enderman");
  public static final EntityType<Entity<EntityMeta>> ENDERMITE = get("endermite");
  public static final EntityType<Entity<EntityMeta>> EVOKER = get("evoker");
  public static final EntityType<Entity<EntityMeta>> EVOKER_FANGS = get("evoker_fangs");
  public static final EntityType<Entity<EntityMeta>> EXPERIENCE_BOTTLE = get("experience_bottle");
  public static final EntityType<Entity<EntityMeta>> EXPERIENCE_ORB = get("experience_orb");
  public static final EntityType<Entity<EntityMeta>> EYE_OF_ENDER = get("eye_of_ender");
  public static final EntityType<Entity<EntityMeta>> FALLING_BLOCK = get("falling_block");
  public static final EntityType<Entity<EntityMeta>> FIREWORK_ROCKET = get("firework_rocket");
  public static final EntityType<Entity<EntityMeta>> FOX = get("fox");
  public static final EntityType<Entity<EntityMeta>> FROG = get("frog");
  public static final EntityType<Entity<EntityMeta>> FURNACE_MINECART = get("furnace_minecart");
  public static final EntityType<Entity<EntityMeta>> GHAST = get("ghast");
  public static final EntityType<Entity<EntityMeta>> GIANT = get("giant");
  public static final EntityType<Entity<EntityMeta>> GLOW_ITEM_FRAME = get("glow_item_frame");
  public static final EntityType<Entity<EntityMeta>> GLOW_SQUID = get("glow_squid");
  public static final EntityType<Entity<EntityMeta>> GOAT = get("goat");
  public static final EntityType<Entity<EntityMeta>> GUARDIAN = get("guardian");
  public static final EntityType<Entity<EntityMeta>> HOGLIN = get("hoglin");
  public static final EntityType<Entity<EntityMeta>> HOPPER_MINECART = get("hopper_minecart");
  public static final EntityType<Entity<EntityMeta>> HORSE = get("horse");
  public static final EntityType<Entity<EntityMeta>> HUSK = get("husk");
  public static final EntityType<Entity<EntityMeta>> ILLUSIONER = get("illusioner");
  public static final EntityType<Entity<EntityMeta>> INTERACTION = get("interaction");
  public static final EntityType<Entity<EntityMeta>> IRON_GOLEM = get("iron_golem");
  public static final EntityType<Entity<EntityMeta>> ITEM = get("item");
  public static final EntityType<Entity<EntityMeta>> ITEM_DISPLAY = get("item_display");
  public static final EntityType<Entity<EntityMeta>> ITEM_FRAME = get("item_frame");
  public static final EntityType<Entity<EntityMeta>> OMINOUS_ITEM_SPAWNER = get("ominous_item_spawner");
  public static final EntityType<Entity<EntityMeta>> FIREBALL = get("fireball");
  public static final EntityType<Entity<EntityMeta>> LEASH_KNOT = get("leash_knot");
  public static final EntityType<Entity<EntityMeta>> LIGHTNING_BOLT = get("lightning_bolt");
  public static final EntityType<Entity<EntityMeta>> LLAMA = get("llama");
  public static final EntityType<Entity<EntityMeta>> LLAMA_SPIT = get("llama_spit");
  public static final EntityType<Entity<EntityMeta>> MAGMA_CUBE = get("magma_cube");
  public static final EntityType<Entity<EntityMeta>> MARKER = get("marker");
  public static final EntityType<Entity<EntityMeta>> MINECART = get("minecart");
  public static final EntityType<Entity<EntityMeta>> MOOSHROOM = get("mooshroom");
  public static final EntityType<Entity<EntityMeta>> MULE = get("mule");
  public static final EntityType<Entity<EntityMeta>> OCELOT = get("ocelot");
  public static final EntityType<Entity<EntityMeta>> PAINTING = get("painting");
  public static final EntityType<Entity<EntityMeta>> PANDA = get("panda");
  public static final EntityType<Entity<EntityMeta>> PARROT = get("parrot");
  public static final EntityType<Entity<EntityMeta>> PHANTOM = get("phantom");
  public static final EntityType<Entity<EntityMeta>> PIG = get("pig");
  public static final EntityType<Entity<EntityMeta>> PIGLIN = get("piglin");
  public static final EntityType<Entity<EntityMeta>> PIGLIN_BRUTE = get("piglin_brute");
  public static final EntityType<Entity<EntityMeta>> PILLAGER = get("pillager");
  public static final EntityType<Entity<EntityMeta>> POLAR_BEAR = get("polar_bear");
  public static final EntityType<Entity<EntityMeta>> POTION = get("potion");
  public static final EntityType<Entity<EntityMeta>> PUFFERFISH = get("pufferfish");
  public static final EntityType<Entity<EntityMeta>> RABBIT = get("rabbit");
  public static final EntityType<Entity<EntityMeta>> RAVAGER = get("ravager");
  public static final EntityType<Entity<EntityMeta>> SALMON = get("salmon");
  public static final EntityType<Entity<EntityMeta>> SHEEP = get("sheep");
  public static final EntityType<Entity<EntityMeta>> SHULKER = get("shulker");
  public static final EntityType<Entity<EntityMeta>> SHULKER_BULLET = get("shulker_bullet");
  public static final EntityType<Entity<EntityMeta>> SILVERFISH = get("silverfish");
  public static final EntityType<Entity<EntityMeta>> SKELETON = get("skeleton");
  public static final EntityType<Entity<EntityMeta>> SKELETON_HORSE = get("skeleton_horse");
  public static final EntityType<Entity<EntityMeta>> SLIME = get("slime");
  public static final EntityType<Entity<EntityMeta>> SMALL_FIREBALL = get("small_fireball");
  public static final EntityType<Entity<EntityMeta>> SNIFFER = get("sniffer");
  public static final EntityType<Entity<EntityMeta>> SNOW_GOLEM = get("snow_golem");
  public static final EntityType<Entity<EntityMeta>> SNOWBALL = get("snowball");
  public static final EntityType<Entity<EntityMeta>> SPAWNER_MINECART = get("spawner_minecart");
  public static final EntityType<Entity<EntityMeta>> SPECTRAL_ARROW = get("spectral_arrow");
  public static final EntityType<Entity<EntityMeta>> SPIDER = get("spider");
  public static final EntityType<Entity<EntityMeta>> SQUID = get("squid");
  public static final EntityType<Entity<EntityMeta>> STRAY = get("stray");
  public static final EntityType<Entity<EntityMeta>> STRIDER = get("strider");
  public static final EntityType<Entity<EntityMeta>> TADPOLE = get("tadpole");
  public static final EntityType<Entity<EntityMeta>> TEXT_DISPLAY = get("text_display");
  public static final EntityType<Entity<EntityMeta>> TNT = get("tnt");
  public static final EntityType<Entity<EntityMeta>> TNT_MINECART = get("tnt_minecart");
  public static final EntityType<Entity<EntityMeta>> TRADER_LLAMA = get("trader_llama");
  public static final EntityType<Entity<EntityMeta>> TRIDENT = get("trident");
  public static final EntityType<Entity<EntityMeta>> TROPICAL_FISH = get("tropical_fish");
  public static final EntityType<Entity<EntityMeta>> TURTLE = get("turtle");
  public static final EntityType<Entity<EntityMeta>> VEX = get("vex");
  public static final EntityType<Entity<EntityMeta>> VILLAGER = get("villager");
  public static final EntityType<Entity<EntityMeta>> VINDICATOR = get("vindicator");
  public static final EntityType<Entity<EntityMeta>> WANDERING_TRADER = get("wandering_trader");
  public static final EntityType<Entity<EntityMeta>> WARDEN = get("warden");
  public static final EntityType<Entity<EntityMeta>> WIND_CHARGE = get("wind_charge");
  public static final EntityType<Entity<EntityMeta>> WITCH = get("witch");
  public static final EntityType<Entity<EntityMeta>> WITHER = get("wither");
  public static final EntityType<Entity<EntityMeta>> WITHER_SKELETON = get("wither_skeleton");
  public static final EntityType<Entity<EntityMeta>> WITHER_SKULL = get("wither_skull");
  public static final EntityType<Entity<EntityMeta>> WOLF = get("wolf");
  public static final EntityType<Entity<EntityMeta>> ZOGLIN = get("zoglin");
  public static final EntityType<Entity<EntityMeta>> ZOMBIE = get("zombie");
  public static final EntityType<Entity<EntityMeta>> ZOMBIE_HORSE = get("zombie_horse");
  public static final EntityType<Entity<EntityMeta>> ZOMBIE_VILLAGER = get("zombie_villager");
  public static final EntityType<Entity<EntityMeta>> ZOMBIFIED_PIGLIN = get("zombified_piglin");
  public static final EntityType<Entity<EntityMeta>> PLAYER = get("player");
  public static final EntityType<Entity<EntityMeta>> FISHING_BOBBER = get("fishing_bobber");

  @SuppressWarnings("unchecked")
  private static <E extends Entity<? extends EntityMeta>> EntityType<E> get(final String key) {
    return (EntityType<E>) Registries.entityTypes().get(Key.MINECRAFT_NAMESPACE + ':' + key);
  }
}
