name: Build and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          chmod +x gradlew;
          ./gradlew check shadowJar;
      - name: Publish
        if: false
        run: |
          ./gradlew publish
        env:
          SONATYPE_USER: "${{ secrets.SONATYPE_USER }}"
          SONATYPE_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sculk-server
          path: server/build/libs

